# Installation method: Home Assistant OS
# Core: 2026.8.2
# Supervisor: 2026.07.5
# Operating System: 18.2
# Frontend: 20260729.7
# ESPHome Current version: 2026.7.4
#


# Board: ESP32-2424S012 Round CYD 1.28" (Guition)
# Definition: definitions/boards/esp32-2424s012/manifest.yaml

esphome:
  name: cyd2424
  friendly_name: cyd2424

esp32:
  variant: esp32c3
  flash_size: 4MB
  framework:
    type: esp-idf

logger:

api:
  encryption: 
    key: !secret cyd2424_api

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: 192.168.68.124
  manual_ip: 
    static_ip: 192.168.68.124
    gateway: 192.168.68.1
    subnet: 255.255.255.0
  ap:
    ssid: !secret cyd2424_ap_ssid
    password: !secret cyd2424_ap_pwd

web_server:
    
captive_portal:
#########################################################

time:
  - platform: homeassistant
    timezone: "America/New_York"
    id: esptime

i2c:
  sda: 4
  scl: 5
  scan: true

spi:
  clk_pin: 6
  mosi_pin: 7
  # miso_pin: 

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

output:
  - platform: ledc
    pin: 3
    id: backlight_pwm

#####################################################################

####  https://esphome.io/components/interval/
interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: lbl_time
          text: !lambda |-
            return id(esptime).now().strftime("%H:%M:%S");
  - interval: 1min
    then:
      - lvgl.label.update:
          id: lbl_date
          text: !lambda |-
            return id(esptime).now().strftime("%Y-%m-%d");
      - lvgl.label.update:
          id: lbl_dow
          text: !lambda |-
            return id(esptime).now().strftime("%A");

#### https://esphome.io/components/sensor/wifi_signal/    
#### https://community.home-assistant.io/t/weather-in-esphome/650188
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s    
    on_value:
      then:
        - lvgl.arc.update: 
            id: arc_wifi
            value: !lambda |-
              return int(x);
        - lvgl.label.update: 
            id: lbl_wifi
            text:
              format: "%.0f dBm"
              args: [x]
  - platform: homeassistant
    name: Current Temperature
    entity_id: weather.forecast_home
    id: cur_temp
    attribute: temperature
    unit_of_measurement: °F
    on_value:
      then:
        - lvgl.label.update: 
            id: lbl_temp
            text:
              format: "%.0f"
              args: [x]
        - lvgl.arc.update:
            id: arc_temp
            value: !lambda |-
              return int(x);

#### https://esphome.io/components/sun/
sun:
  latitude: 39.6837
  longitude: -75.7497
              
text_sensor:
  - platform: sun
    name: Sun Next Sunrise
    id: sunrise
    type: sunrise
    on_value:
      then:
        - lvgl.label.update: 
            id: lbl_sunrise
            text: !lambda |-
              struct tm dt = {};
              strptime(id(sunrise).state.c_str(), "%X", &dt);
              char buffer[10];
              strftime(buffer, sizeof(buffer), "%X", &dt);
              return {std::string(buffer)};
  - platform: sun
    name: Sun Next Sunset
    id: sunset
    type: sunset
    on_value:
      then:
        - lvgl.label.update: 
            id: lbl_sunset
            text: !lambda |-
              struct tm dt = {};
              strptime(id(sunset).state.c_str(), "%X", &dt);
              char buffer[10];
              strftime(buffer, sizeof(buffer), "%X", &dt);
              return {std::string(buffer)};
#####################################################################
display:
  - platform: mipi_spi
    id: my_display
    model: GC9A01A
    dc_pin:
      number: 2
      ignore_strapping_warning: true
    cs_pin: 10
    reset_pin: 
      number: 1
      allow_other_uses: true
    dimensions: 240x240
    invert_colors: true
    update_interval: never
    auto_clear_enabled: false

touchscreen:
  platform: cst816
  id: my_touch
  update_interval: 50ms
  interrupt_pin: 0
  reset_pin:
    number: 1
    allow_other_uses: true
  on_touch: 
    - light.turn_on: 
        id: backlight
        brightness: 100%
  on_release:
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
###########################################################
lvgl:
  rotation: 0
  touchscreens:
    - my_touch
  buffer_size: 25%
  on_idle:
    timeout: 600s
    then:
      - light.turn_off: backlight
      - lvgl.pause:
########################################################
  pages:
    - id: canvas_1
      bg_color: 0x111827
      pad_all: 0
      scrollbar_mode: "OFF"
      widgets:
        - arc:
            id: arc_temp
            x: 0
            y: 0
            width: 240
            height: 240
            align: CENTER
            value: 50
            min_value: 0
            max_value: 100
            adjustable: true
            start_angle: 135
            end_angle: 260
            arc_color: 0x363B45
            arc_width: 15
            indicator:
              arc_color: 0x0758DA
              arc_width: 15

        - arc:
            id: arc_wifi
            x: 0
            y: 0
            width: 240
            height: 240
            align: CENTER
            value: -50
            min_value: -100
            max_value: 0
            adjustable: true
            start_angle: 280
            end_angle: 45
            arc_color: 0x363B45
            arc_width: 15
            indicator:
              arc_color: 0x078D24
              arc_width: 15

        - label:
            id: lbl_time
            x: 0
            y: 0
            align: CENTER
            text: "15:14:13"
            text_color: 0x8B1D1D
            text_font: montserrat_40

        - label:
            id: lbl_date
            x: 40
            y: 150
            text: "2026-08-17"
            text_color: 0x078D24
            text_font: montserrat_12

        - label:
            id: lbl_dow
            x: 136
            y: 150
            text: "Wednesday"
            text_color: 0x078D24
            text_font: montserrat_12

        - button:
            id: btn_next
            x: 0
            y: -40
            width: 50
            height: 30
            align: BOTTOM_MID
            bg_color: 0x000000
            shadow_width: 2
            shadow_color: 0xBD1499
            shadow_opa: 50%
            shadow_offset_y: -1
            shadow_spread: 2
            on_click:
              then:
                - lvgl.page.next: 
                    id: canvas_2
            widgets:
              - label:
                  id: icn_next
                  x: 0
                  y: 0
                  align: CENTER
                  text: "\uF054"
                  text_font: montserrat_24
                  text_align: CENTER
                  text_color: 0xFFFFFF

        - label:
            id: lv_icon_6
            x: 0
            y: 40
            width: 20
            height: 20
            align: TOP_MID
            text: "\uF015"
            text_font: montserrat_24
            text_align: CENTER
            text_color: 0xFFFFFF

        - label:
            id: lbl_temp
            x: 65
            y: 210
            width: 30
            height: 10
            text: "75 *F"
            text_color: 0xFFFFFF
            text_font: montserrat_10

        - label:
            id: lbl_wifi
            x: 140
            y: 210
            width: 50
            height: 15
            text: "-45 dBm"
            text_color: 0xFFFFFF
            text_font: montserrat_10

    - id: canvas_2
      bg_color: 0x111827
      pad_all: 0
      scrollbar_mode: "OFF"
      widgets:
        - label:
            id: lv_icon_9
            x: 0
            y: 40
            align: TOP_MID
            text: "\uF06E"
            text_font: montserrat_24
            text_align: CENTER
            text_color: 0xFFFFFF

        - button:
            id: btn_next2
            x: 0
            y: -40
            width: 50
            height: 30
            align: BOTTOM_MID
            bg_color: 0x000000
            shadow_width: 2
            shadow_color: 0xBD1499
            shadow_opa: 50%
            shadow_offset_y: -1
            shadow_spread: 2
            on_click:
              then:
                - lvgl.page.next: 
                    id: canvas_1
            widgets:
              - label:
                  id: icn_next2
                  x: 0
                  y: 0
                  align: CENTER
                  text: "\uF054"
                  text_font: montserrat_24
                  text_align: CENTER
                  text_color: 0xFFFFFF

        - label:
            id: lbl_rise
            x: 40
            y: 85
            text: "Sun Rise"
            text_color: 0xFFFFFF

        - label:
            id: lbl_set
            x: 40
            y: 112
            text: "Sun Set"
            text_color: 0xFFFFFF

        - label:
            id: lbl_sunrise
            x: 140
            y: 85
            width: 70
            height: 16
            text: "06:12:13"
            text_color: 0xFFFFFF

        - label:
            id: lbl_sunset
            x: 140
            y: 112
            width: 70
            height: 16
            text: "07:12:13"
            text_color: 0xFFFFFF