esphome:
  name: picow
  friendly_name: picow

#
# picow-hello.yaml
# Copyright (C) 2025 KW Services.
# MIT License
# Home Assistant ESPHome 7.5
# Raspberry Pi Pico #(RP2040)
# LVGL 8.4
#

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret picow_api_key

ota:
  - platform: esphome
    password: !secret picow_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # manual_ip: 
  #   static_ip: !secret picow_ip
  #   gateway: !secret picow_gw
  #   subnet: 255.255.255.0

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: !secret picow_ap_ssid
    password: !secret picow_ap_password

# Example configuration entry
# output:
#   - platform: gpio
#     pin: GPIO03
#     id: 'generic_out2'
# switch:
#   - platform: output
#     name: "Generic Output2"
#     output: 'generic_out2'

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19
  miso_pin: GPIO16
  interface: spi

display:
- platform: ili9xxx
  model: ili9341
  id: my_display
  dc_pin: GPIO00
  reset_pin: GPIO01
  cs_pin: GPIO17
  rotation: 90
  invert_colors: false

touchscreen:
- platform: xpt2046
  id: my_touchscreen
  cs_pin: GPIO21
  update_interval: 50ms
  threshold: 400
  transform:
    mirror_x: True
    mirror_y: False
    swap_xy: True
  calibration:
    x_min: 281
    x_max: 3848
    y_min: 347
    y_max: 3878


# lvgl
lvgl:
  buffer_size: 10%
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  pages:
    - id: main_page
      widgets:
        - label:
            align: CENTER
            text: 'Hello World!'
        - switch:
            id: switch_id
            x: 50
            y: 50
        - slider:
            x: 10
            y: 200
            width: 220
            id: slider_id
            value: 75
            min_value: 0
            max_value: 100
