esphome:
  name: picow
  friendly_name: picow

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret picow_api_key

ota:
  - platform: esphome
    password: !secret picow_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: !secret picow_ip
    gateway: !secret picow_gw
    subnet: 255.255.255.0

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: !secret picow_ap_ssid
    password: !secret picow_ap_password

# Example configuration entry
# output:
#   - platform: gpio
#     pin: GPIO03
#     id: 'generic_out2'
# switch:
#   - platform: output
#     name: "Generic Output2"
#     output: 'generic_out2'

sensor:
  - platform: adc
    pin: TEMPERATURE
    id: core_temp
    name: "Core Temperature"
    unit_of_measurement: "°C"
    on_value:
      - lvgl.indicator.update:
          id: temperature_needle
          value: !lambda return 27 - (x - 0.706f) / 0.001721f;
      - lvgl.label.update:
          id: temperature_text
          text:
            format: "%.1f°C"
            args: [ 'x' ]

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19
  miso_pin: GPIO16
  interface: spi

display:
- platform: ili9xxx
  model: ili9341
  id: my_display
  dc_pin: GPIO00
  reset_pin: GPIO01
  cs_pin: GPIO17
  rotation: 90
  invert_colors: false

touchscreen:
- platform: xpt2046
  id: my_touchscreen
  cs_pin: GPIO21
  update_interval: 50ms
  threshold: 400
  transform:
    mirror_x: True
    mirror_y: False
    swap_xy: True
  calibration:
    x_min: 281
    x_max: 3848
    y_min: 347
    y_max: 3878



# lvgl
lvgl:
  buffer_size: 10%
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  pages:
    - id: meter_page
      bg_color: 0x0
      widgets:
        - meter:
            align: CENTER
            height: 180
            width: 180
            scales:
              - range_from: -100 # scale for the needle value
                range_to: 400
                angle_range: 240
                rotation: 150
                indicators:
                  - line:
                      id: temperature_needle
                      width: 2
                      color: 0xFF0000
                      r_mod: -4
                  - tick_style:
                      start_value: -10
                      end_value: 40
                      color_start: 0x0000bd
                      color_end: 0xbd0000
                      width: 1
              - range_from: -10 # scale for the value labels
                range_to: 40
                angle_range: 240
                rotation: 150
                ticks:
                  width: 1
                  count: 51
                  length: 10
                  color: 0x000000
                  major:
                    stride: 5
                    width: 2
                    length: 10
                    color: 0x404040
                    label_gap: 10
            widgets:
              - label:
                  id: temperature_text
                  text: "-.-°C"
                  align: CENTER
                  y: 45
              - label:
                  text: "Temperature"
                  align: CENTER
                  y: 65
