esphome:
  name: esp32p486
  friendly_name: esp32p486

esp32:
  board: esp32-p4-evboard
  cpu_frequency: 400MHZ
  framework:
    type: esp-idf
    advanced: 
      enable_idf_experimental_features: True
  flash_size: 32MB

psram:
  speed: 200MHz

# Enable logging
logger:
  level: DEBUG
  logs: 
    lvgl: INFO
  hardware_uart: UART0

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp32p486_api_key

ota:
  - platform: esphome
    password: !secret esp32p486_ota_password

esp_ldo:
  - channel: 3
    voltage: 2.5V

# ethernet or wifi

# ethernet:
#   type: IP101
#   mdc_pin: 31
#   mdio_pin: 52
#   clk: 
#     mode: CLK_EXT_IN
#     pin: 50
#   power_pin: 51
#   phy_addr: 1

esp32_hosted:
  active_high: True
  variant: ESP32C6
  reset_pin: 54
  cmd_pin: 19
  clk_pin: 18
  d0_pin: 14
  d1_pin: 15
  d2_pin: 16
  d3_pin: 17

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: 192.168.68.104
  manual_ip: 
    static_ip: 192.168.68.104
    gateway: 192.168.68.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esp32p486_ap_ssid
    password: !secret esp32p486_ap_password
  on_connect: 
    then:
      - lvgl.label.update:
          id: wifi_comm_id
          text_color: 0xffffff
      - lvgl.label.update:
          id: wifi_comm_id2
          text_color: 0xffffff

# Enable web server
web_server:
  port: 80
  # auth:
  #   username: !secret central_ws_user
  #   password: sp!secret central_ws_password

captive_portal:
#################################################################

display:
  - platform: mipi_dsi
    model: WAVESHARE-P4-86-PANEL
    reset_pin:
      number: 27
      inverted: false

i2c:
  - sda: 7
    scl: 8
    scan: True
    frequency: 400kHz
    id: i2c_bus

touchscreen:
  - platform: gt911
    id: mytouchscreen
    on_release:
    - if:
        condition: lvgl.is_paused
        then:
          - logger.log: "LVGL resuming"
          - light.turn_on: display_backlight
          - lvgl.resume:
          - lvgl.widget.redraw:

output:
  - platform: ledc
    id: backlight_
    pin: GPIO26
    frequency: 100Hz
    inverted: true
    min_power: 0.0
    max_power: 0.8 # To prevent overheating due to excessive lighting

switch:
  - platform: gpio
    name: Relay 0
    id: relay_0
    pin: 32
    on_turn_on:
        - lvgl.button.update:
            id: first
            state:
              checked: true
        - logger.log: "Switch Turned On!"
    on_turn_off:
      then:
        - lvgl.button.update:
            id: first
            state:
              checked: false
        - logger.log: "Switch Turned Off!"
  - platform: gpio
    name: Relay 1
    id: relay_1
    pin: 46
    on_turn_on:
        - lvgl.button.update:
            id: second
            state:
              checked: true
        - logger.log: "Switch Turned On!"
    on_turn_off:
      then:
        - lvgl.button.update:
            id: second
            state:
              checked: false
        - logger.log: "Switch Turned Off!"

light:
  - platform: monochromatic
    name: Display Backlight
    output: backlight_
    id: display_backlight
    restore_mode: ALWAYS_ON

font:
    #
    #  This font is acquired directly from google
    #
  - file: "gfonts://Roboto"
    id: roboto
    size: 50
    bpp: 4
    #
    #  Note:  This file must reside on the Home Assistant system in a folder within esphome
    #         See our GitHub site.
    #
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: mdi
    size: 80
    bpp: 4
    glyphs: [
      "\U000F0335", # mdi-lightbulb
      "\U000F0336", # mdi-lightbulb-outline
      "\U000F0210", # mdi-fan
      "\U000F081D", # mdi-fan-off
      "\U000F05A9", # mdi-wifi
      "\U000F0B0B", # mdi-alpha-d-box
      "\U000F0BF4", # mdi-alpha-d-box-outline  
      ]

#######################################

lvgl:
  id: lvgl_component
  buffer_size: 100%
  byte_order: little_endian
  touchscreens:
    - touchscreen_id: mytouchscreen
      long_press_time: 5000ms
      long_press_repeat_time: 400ms
  on_idle:
  - timeout: 100s
    then:
      - light.turn_off: display_backlight
      - lvgl.pause:
  top_layer:
    widgets:
      - obj:
          id: cont_bottom
          x: 30
          y: 590
          width: 660
          height: 90
          bg_opa: TRANSP
          border_color: 0x4B5563
          border_width: 0
          radius: 8
          layout:
            type: FLEX
            flex_flow: ROW
            flex_align_cross: CENTER
          widgets:
            - button:
                id: btn_previous
                align: center
                width: 310
                height: 60
                bg_color: 0x4F46E5
                border_color: 0x70A6C1
                widgets:
                  - label:
                      text: "Previous"
                      text_color: 0xFFFFFF
                      text_font: montserrat_32
                on_press:
                  then:
                    - lvgl.page.previous
            - button:
                id: btn_next
                align: center
                width: 310
                height: 60
                bg_color: 0x4F46E5
                border_color: 0x70A6C1
                widgets:
                  - label:
                      text: "Next"
                      text_color: 0xFFFFFF
                      text_font: montserrat_32
                on_press:
                  then:
                    - lvgl.page.next
  pages:
    - id: page1
      bg_color: 0x000000
      widgets:
        - obj:
            id: cont_top
            x: 30
            y: 0
            width: 660
            height: 90
            bg_opa: TRANSP
            border_color: 0x4B5563
            border_width: 0
            radius: 8
            layout:
              type: FLEX
              flex_flow: ROW
              flex_align_cross: CENTER
            widgets:
              - label:
                  id: title
                  width: 500
                  height: 50
                  align: center
                  text: "Control Panel"
                  text_color: 0xffff00
                  text_font: roboto
              - label:
                  id: wifi_comm_id
                  width: 80
                  height: 40
                  align: center
                  text: "\U000F05A9"
                  bg_color: 0xC0C0C0
                  text_font: mdi
        - obj:
            id: cont_mid
            x: 30
            y: 110
            width: 660
            height: 480
            bg_opa: TRANSP
            border_color: 0x4B5563
            border_width: 1
            radius: 8
            layout:
              type: FLEX
              flex_flow: COLUMN_WRAP
              flex_align_cross: CENTER
            widgets:
              - button:
                  id: first
                  width: 620
                  height: 144
                  bg_color: 0xc0c0c0  #0x4F46E5
                  checkable: true
                  widgets:
                    - label:
                        id: lbl_icon_first
                        text: "\U000F0336"
                        text_font: mdi
                        text_color: 0x0
                        align: TOP_LEFT
                    - label:
                        id: lbl_first
                        text: "Relay 0"
                        text_color: 0x0
                        text_font: montserrat_32
                        align: BOTTOM_LEFT
                  on_value:
                    - if: 
                        condition:
                          lambda: |-
                            return x == true;
                        then:
                          - lvgl.label.update:
                              id: lbl_icon_first
                              text: "\U000F0335"
                              text_font: mdi
                              text_color: 0xffffff
                              align: TOP_LEFT
                    - if: 
                        condition:
                          lambda: |-
                            return x == false;
                        then:
                          - lvgl.label.update:
                              id: lbl_icon_first
                              text: "\U000F0336"
                              text_font: mdi
                              text_color: 0x0
                              align: TOP_LEFT
                  on_click:
                    then:
                      - switch.toggle: relay_0
              - button:
                  id: second
                  width: 620
                  height: 144
                  bg_color: 0xc0c0c0  #0x4F46E5
                  checkable: true
                  widgets:
                    - label:
                        id: lbl_icon_sec
                        text: "\U000F081D"
                        text_font: mdi
                        text_color: 0x0
                        align: TOP_LEFT
                    - label:
                        id: lbl_sec
                        text: "Relay 1"
                        text_font: montserrat_32
                        text_color: 0x0
                        align: BOTTOM_LEFT
                  on_value:
                    - if: 
                        condition:
                          lambda: |-
                            return x == true;
                        then:
                          - lvgl.label.update:
                              id: lbl_icon_sec
                              text: "\U000F0210"
                              text_font: mdi
                              text_color: 0xffffff
                              align: TOP_LEFT
                    - if: 
                        condition:
                          lambda: |-
                            return x == false;
                        then:
                          - lvgl.label.update:
                              id: lbl_icon_sec
                              text: "\U000F081D"
                              text_font: mdi
                              text_color: 0x0
                              align: TOP_LEFT
                  on_click:
                    then:
                      - switch.toggle: relay_1
              - obj:
                  id: third
                  width: 620
                  height: 144
                  bg_color: 0x0
                  border_width: 2
                  widgets:
                    - label:
                        id: lbl_four
                        text: "Future"
                        text_font: montserrat_32
                        text_color: 0xffffff
                        align: BOTTOM_LEFT
    - id: page2
      bg_color: 0x000000
      widgets:
        - obj:
            id: cont_top2
            x: 30
            y: 0
            width: 660
            height: 90
            bg_opa: TRANSP
            border_color: 0x4B5563
            border_width: 0
            radius: 8
            layout:
              type: FLEX
              flex_flow: ROW
              flex_align_cross: CENTER
            widgets:
              - label:
                  id: title2
                  width: 500
                  height: 50
                  align: center
                  text: "Controls - Page 2"
                  text_color: 0xffff00
                  text_font: roboto
              - label:
                  id: wifi_comm_id2
                  width: 80
                  height: 40
                  align: center
                  text: "\U000F05A9"
                  bg_color: 0xC0C0C0
                  text_font: mdi
            
http_request:
  verify_ssl: False