esphome:
  name: esp32cam2
  friendly_name: esp32cam2
  platformio_options: 
    platform: |-
      espressif32
    build_flags:
      -DBOARD_HAS_PSRAM
      -mfix-esp32-psram-cache-issue

#######################
# Based on ESP32S3_EYE
#######################

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework:
    type: arduino
  flash_size: 8MB

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: foriot_apikey
    
ota:
  - platform: esphome
    password: foriot_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: 192.168.68.91
    gateway: 192.168.68.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Cam Fallback Hotspot"
    password: foriot_ap_password

# Enable web server
web_server:
  port: 80
  # auth:
  #   username: !secret central_ws_user
  #   password: sp!secret central_ws_password

captive_portal:

##########################################################################

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"  
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s 

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
    chipset: ws2812
    name: "Cam2 light"

# ESP32-CAM
i2c:
  - id: camera_i2c
    sda: GPIO4
    scl: GPIO5
esp32_camera:
  id: espcam
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  frame_buffer_location: PSRAM
  # Image settings
  name: Cam2
  #resolution: 320x240 # Example resolution (e.g., 640x480, 1024x768, 1280x1024)
  #resolution: 640x480 # Example resolution (e.g., 640x480, 1024x768, 1280x1024)
  resolution: 1024x768 # Example resolution (e.g., 640x480, 1024x768, 1280x1024)
  jpeg_quality: 10
  # Frame Settings
  max_framerate: 5fps
  idle_framerate: 0.1fps
  frame_buffer_count: 2
