esphome:
  name: testcam1
  friendly_name: testcam1

#######################
# Based on AI-Thinker
#######################

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: inland_apikey

ota:
  - platform: esphome
    password: inland_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: 192.168.68.93
    gateway: 192.168.68.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testcam1 Fallback Hotspot"
    password: inland_ap_password

# Enable web server
web_server:
 port: 80
  # auth:
  #   username: !secret central_ws_user
  #   password: sp!secret central_ws_password

captive_portal:

##########################################################################

sensor:
  - platform: internal_temperature
    name: "Internal Temperature" 
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s  

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: testcam1 light

# Example configuration entry
i2c:
  - id: camera_i2c
    sda: GPIO26
    scl: GPIO27

esp32_camera:
  id: espcam
  external_clock:
    pin: GPIO0  
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # Image settings
  name: test-cam1
  #resolution: 320x240 # Example resolution (e.g., 640x480, 1024x768, 1280x1024)
  #resolution: 640x480 # Example resolution (e.g., 640x480, 1024x768, 1280x1024)
  resolution: 1024x768 # Example resolution (e.g., 640x480, 1024x768, 1280x1024)
  jpeg_quality: 10   # Adjust for quality vs. file size (1 is lowest, 100 is highest, defaults to 80) 
  max_framerate: 10 fps
  idle_framerate: 0.1 fps
  frame_buffer_count: 2
  
  