esphome:
  name: central
  friendly_name: Central

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret central_api_key

ota:
  - platform: esphome
    password: !secret central_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: !secret central_ip
    gateway: !secret central_gw
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret central_ap_ssid
    password: !secret central_ap_password

# configure HA definition  




# Enable web server
web_server:
  port: 80
  # auth:
  #   username: !secret central_ws_user
  #   password: sp!secret central_ws_password

captive_portal:

spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11
  miso_pin: GPIO13
  interface: spi2

display:
- platform: ili9xxx
  model: ili9341
  id: my_display
  dc_pin: GPIO07
  reset_pin: GPIO04
  cs_pin: GPIO10
  rotation: 90   #  0=Portrait 90=Landscape
  invert_colors: false

touchscreen:
- platform: xpt2046
  id: my_touchscreen
  cs_pin: GPIO05
  interrupt_pin: GPIO15
  update_interval: 50ms
  threshold: 400
  transform:     
    mirror_x: True
    mirror_y: False
    swap_xy: True
  #rot=0
  # transform:
  #   mirror_x: True
  #   mirror_y: True
  #   swap_xy: False
  calibration:
    x_min: 281
    x_max: 3848
    y_min: 347
    y_max: 3878

#### UI #####################################################

# lvgl
lvgl:
  buffer_size: 25%
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  pages:
    - id: main_page
      bg_color: 0x0
      widgets:
        - label:
            align: CENTER
            text: 'Hello World!'
            text_color: 0xFFFFFF
            text_font: montserrat_36
        - switch:
            id: switch_id
            x: 50
            y: 50
            knob:
              bg_color: 0xFFA500          
        - slider:
            x: 10
            y: 200
            width: 290
            id: slider_id
            value: 100
            min_value: 0
            max_value: 100
            knob:
              bg_color: 0x90EE90
        - button:
            id: button_off
            x: 150
            y: 15
            width: 120
            height: 50
            bg_color: 0x00FFFF
            widgets:
              - label: 
                  align: CENTER
                  text_color: 0x0
                  text_font: montserrat_24
                  text: "LED Off"
