esphome:
  name: central
  friendly_name: Central

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret central_api_key

ota:
  - platform: esphome
    password: !secret central_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: !secret central_ip
    gateway: !secret central_gw
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret central_ap_ssid
    password: !secret central_ap_password

# configure HA definition
sensor:
  - platform: internal_temperature
    id: core_temp
    name: "Core Temperature"
    unit_of_measurement: "°C"
    on_value:
      - lvgl.indicator.update:
          id: temperature_needle
          value: !lambda return x; 
      - lvgl.label.update:
          id: temperature_text
          text:
            format: "%.1f°C"
            args: [ 'x' ]

# Enable web server
web_server:
  port: 80
  # auth:
  #   username: !secret central_ws_user
  #   password: sp!secret central_ws_password

captive_portal:

spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11
  miso_pin: GPIO13
  interface: spi2

display:
- platform: ili9xxx
  model: ili9341
  id: my_display
  dc_pin: GPIO07
  reset_pin: GPIO04
  cs_pin: GPIO10
  rotation: 90   #  0=Portrait 90=Landscape
  invert_colors: false

touchscreen:
- platform: xpt2046
  id: my_touchscreen
  cs_pin: GPIO05
  interrupt_pin: GPIO15
  update_interval: 50ms
  threshold: 400
  transform:     
    mirror_x: True
    mirror_y: False
    swap_xy: True
  #rot=0
  # transform:
  #   mirror_x: True
  #   mirror_y: True
  #   swap_xy: False
  calibration:
    x_min: 281
    x_max: 3848
    y_min: 347
    y_max: 3878

#### UI #####################################################


# lvgl
lvgl:
  buffer_size: 25%
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  pages:
    - id: main_page
      bg_color: 0x0
      widgets:
        - meter:
            align: CENTER
            height: 180
            width: 180
            scales:
              - range_from: -10 # scale for the needle value
                range_to: 60
                angle_range: 240
                rotation: 150
                indicators:
                  - line:
                      id: temperature_needle
                      width: 2
                      color: 0xFF0000
                      r_mod: -4
                  - tick_style:
                      start_value: -10
                      end_value: 60
                      color_start: 0x0000bd
                      color_end: 0xbd0000
                      width: 1
              - range_from: -10 # scale for the value labels
                range_to: 60
                angle_range: 240
                rotation: 150
                ticks:
                  width: 1
                  count: 51
                  length: 10
                  color: 0x000000
                  major:
                    stride: 5
                    width: 2
                    length: 10
                    color: 0x404040
                    label_gap: 10
            widgets:
              - label:
                  id: temperature_text
                  text: "-.-°C"
                  align: CENTER
                  y: 45
              - label:
                  text: "Temperature"
                  align: CENTER
                  y: 65         
