esphome:
  name: esptemp
  friendly_name: esptemp

esp32:
  board: esp32dev
  framework:
    type: esp-idf


#
# esptemp.yaml
# Copyright (C) 2025 KW Services.
# MIT License
# Home Assistant ESPHome 7.5
# Raspberry Pi Pico #(RP2040)
# LVGL 8.4
#

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esptemp_apikey

ota:
  - platform: esphome
    password: !secret esptemp_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: !secret esptemp_ip
    gateway: !secret esptemp_gw
    subnet: 255.255.255.0
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: esptemp_ap_ssid
    password: esptemp_ap_password

# Enable web server
web_server:
  port: 80
  # auth:
  #   username: !secret central_ws_user
  #   password: sp!secret central_ws_password

captive_portal:

#### Hardware ######################################################################

i2c:
  - sda: 27
    scl: 22
    scan: true

spi:
  - id: tft
    clk_pin: 14
    mosi_pin: 13
    miso_pin:
      number: 12
      ignore_strapping_warning: true
  - id: touch
    clk_pin: 25
    mosi_pin: 32
    miso_pin: 39

output:
  - id: backlight_pwm
    platform: ledc
    pin: 21
  - id: output_red
    platform: ledc
    pin: 4
    inverted: true
  - id: output_green
    platform: ledc
    pin: 16
    inverted: true
  - id: output_blue
    platform: ledc
    pin: 17
    inverted: true

light:
  - id: backlight
    platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    restore_mode: ALWAYS_ON
  - id: led
    platform: rgb
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF

display:
  - id: main_display
    platform: ili9xxx
    model: ILI9341
    spi_id: tft
    cs_pin:
      number: 15
      ignore_strapping_warning: true
    dc_pin:
      number:  2
      ignore_strapping_warning: true
    invert_colors: false
    rotation: 90
    update_interval: never
    auto_clear_enabled: false

touchscreen:
  - id: main_touchscreen
    platform: xpt2046
    spi_id: touch
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860
    transform:
      mirror_x: False
      mirror_y: False
      swap_xy: True

#### SENSORS #####################################################################

#### FONT ########################################################################

##### UI #########################################################################

# lvgl
lvgl:
  buffer_size: 25%
  displays:
    - main_display
  touchscreens:
    - main_touchscreen
  pages:
    - id: main_page
      bg_color: 0x0
      widgets:
        - label:
            align: CENTER
            text: 'Hello World!'
            text_color: 0xFFFFFF
            text_font: montserrat_36
        - switch:
            id: switch_id
            x: 50
            y: 50
            knob:
              bg_color: 0xFFA500 
            on_value:
              then:
                - output.turn_on: offboard_led
                - switch.turn_on: sw_out
                - light.turn_on:
                    id: onboard_light
                    red: 0%
                    green: 100%
                    blue: 0%
                    brightness: 50%             
        - slider:
            x: 10
            y: 200
            width: 290
            id: slider_id
            value: 100
            min_value: 0
            max_value: 100
            knob:
              bg_color: 0x90EE90